spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  rabbitmq:
    host: rabbitmq-server
    port: 5672
    username: root
    password: root
    virtual-host: /
  sleuth:
    sampler:
      percentage: 1.0   # 定义抽样比率，默认为0.1 
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka:8761/eureka  
  instance:
    lease-renewal-interval-in-seconds: 30 # 设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90 # 如果现在超过了5秒的间隔（默认是90秒）
    instance-id: cloud-gateway-701.com  # 在信息列表时显示主机名称
    prefer-ip-address: true     # 访问的路径变为IP地址  
zuul:     
  ignoredServices: '*'
  routes:
    koo-cloud-provider-uac: /user-proxy/**
    koo-cloud-server-monitor: /monitor-proxy/**
    
    
    
    
    
    
    
    
    
    
    