spring:
  profiles:
    active: beta
  rabbitmq:
      port: 5672
      hostname: cloud-rabbitmq
      username: root
      password: root  
  redis:
    host: cloud-redis
    password: 123456
    port: 6379
    timeout: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10
    min-idle: 10
    max-active: 20
    test-on-borrow: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://cloud-eureka:8761/eureka/
koocloud:
  server:    
    eureka:
      port: 8761
      hostname: cloud-eureka
      serviceUrl: http://cloud-eureka:8761/eureka/
    discovery:
      port: 8800
      hostname: cloud-config
      serviceUrl: http://cloud-config:8800    
    monitor:
      port: 8810
      hostname: cloud-monitor
      serviceUrl: http://cloud-monitor:8810
    zipkin:
      port: 8820
      hostname: cloud-zipkin
      serviceUrl: http://cloud-zipkin:8820
    gateway:
      port: 8860
      hostname: http://cloud-gateway:8860
    provider:
      uac:
        port: 801
        hostname: cloud-uac    
  auth:
    jwt:
      expiredRemainMinutes: 20
      expiredMinutes: 120



