spring:  
  application:
    name: koo-cloud-server-zipkin
  rabbitmq:
    host: cloud-rabbitmq
    port: 5672
    username: root
    password: root
    virtual-host: /
  datasource:
    schema: classpath:/zipkin.sql
    url: jdbc:mysql://cloud-mysql:3306/zipkin?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false
    zipkin:
      locator:
        discovery:
          enabled: true
zipkin:
    storage:  # 设置zipkin收集的信息通过mysql进行存储
      type: mysql    
info:
  owner: kingkoo1985@gmail.com
  version: $project.verson$     
  app.name: koo-cloud
  company.name: koo-cloud-company
  build.artifactId: $project.artifactId$
  build.version: $project.verson$     
#logging 配置信息
logging:
  level:
    root: info
  path: logs/
  file: ${spring.application.name}.log 